// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://boemnndqqjkjksjpyhbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvZW1ubmRxcWpramtzanB5aGJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MzQzNTYsImV4cCI6MjA2OTIxMDM1Nn0.tPdYkOppnKl8ecZ3Hqcm2Pk8EG3oEPL1-HYdQIWAHoc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});